// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/resendlabs/resend-go/pkg/models/shared"
	"net/http"
)

type SendEmailResponse struct {
	ContentType string
	// OK
	SendEmailResponse *shared.SendEmailResponse
	StatusCode        int
	RawResponse       *http.Response
}
