// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Email - Email to send
type Email struct {
	// Bcc recipient email address. Multiple addresses are comma separated. Max 50.
	Bcc *string `json:"bcc,omitempty"`
	// Cc recipient email address. Multiple addresses are comma separated. Max 50.
	Cc *string `json:"cc,omitempty"`
	// Sender email address. To include a friendly name, use the format "Your Name <sender@domain.com>".
	From string `json:"from"`
	// The HTML version of the message.
	HTML *string `json:"html,omitempty"`
	// Reply-to email address.
	ReplyTo *string `json:"reply_to,omitempty"`
	// Email subject.
	Subject string `json:"subject"`
	// The plain text version of the message.
	Text *string `json:"text,omitempty"`
	// Recipient email address. Multiple addresses are comma separated. Max 50.
	To string `json:"to"`
}
