name: Generate

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *

jobs:
  generate:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - uses: speakeasy-api/sdk-generation-action@v13
        with:
          force: ${{ github.event.inputs.force }}
          speakeasy_version: latest
          openapi_doc_location: https://raw.githubusercontent.com/resendlabs/resend-openapi/main/resend.yaml
          languages: |-
            - go
          mode: pr
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
